language: node_js
node_js: stable
#cache: 
#  directories:
#    - node_modules
#    - public
script:
  - export TZ='Asia/Shanghai'
  - npm install
  - cd themes/next
  - npm install
  - cd ../../
  - hexo generate
  - echo "www.li-rui.top" > public/CNAME
  - echo "google.com, pub-1534231526661590, DIRECT, f08c47fec0942fa0" > public/ads.txt
  - git config user.name "sunnoy"
  - git config user.email "${email}"
  - cd public
  - git init
  - git add .
  - git commit -m "travis auto at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${CI}@github.com/sunnoy/sunnoy.github.io.git" master:master
